#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 28 21:59:50 2018

@author: manish
"""

import urllib.request as url12

url=("https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India")

page=url12.urlopen(url)

from bs4 import BeautifulSoup

soup1=BeautifulSoup(page,"lxml")
print(soup1.title)

right_table=soup1.find("table", {"class":"wikitable sortable plainrowheaders"})

A=[]
B=[]
C=[]
D=[]
E=[]
F=[]
G=[]

for row in right_table.find_all("tr"):
    cells = row.find_all('td')
    states=row.find_all('th') #To store second column data
    if len(cells)==6: #Only extract table body not heading
        A.append(cells[0].find(text=True))
        B.append(states[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))
        E.append(cells[3].find(text=True))
        F.append(cells[4].find(text=True))
        G.append(cells[5].find(text=True))
        
        
#import pandas to convert list to data frame
import pandas as pd
df=pd.DataFrame(A,columns=['Number'])
df['State/UT']=B
df['Admin_Capital']=C
df['Legislative_Capital']=D
df['Judiciary_Capital']=E
df['Year_Capital']=F
df['Former_Capital']=G
df


df2=pd.DataFrame(df)